[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true

[profile.zksync]
src = 'src'
test = 'zksync'
script = 'scripts'
libs = ['lib']
solc = '0.8.20'
fs_permissions = [{ access = "write", path = "./reports" }]
ffi = true
evm_version = 'shanghai'

[profile.zksync.zksync]
compile = true
optimizer_mode = '3'
zksolc = '1.5.7'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
polygon = "${RPC_POLYGON}"
polygon_amoy = "${RPC_POLYGON_AMOY}"
avalanche = "${RPC_AVALANCHE}"
avalanche_fuji = "${RPC_AVALANCHE_FUJI}"
arbitrum = "${RPC_ARBITRUM}"
arbitrum_sepolia = "${RPC_ARBITRUM_SEPOLIA}"
fantom = "${RPC_FANTOM}"
fantom_testnet = "${RPC_FANTOM_TESTNET}"
optimism = "${RPC_OPTIMISM}"
optimism_sepolia = "${RPC_OPTIMISM_SEPOLIA}"
harmony = "${RPC_HARMONY}"
sepolia = "${RPC_SEPOLIA}"
scroll = "${RPC_SCROLL}"
scroll_sepolia = "${RPC_SCROLL_SEPOLIA}"
metis = "${RPC_METIS}"
base = "${RPC_BASE}"
base_sepolia = "${RPC_BASE_SEPOLIA}"
bnb = "${RPC_BNB}"
gnosis = "${RPC_GNOSIS}"
zkEVM = "${RPC_ZKEVM}"
celo = "${RPC_CELO}"
zksync = "${RPC_ZKSYNC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_MAINNET}", chain = 1 }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", chain = 10 }
avalanche = { key = "${ETHERSCAN_API_KEY_AVALANCHE}", chain = 43114 }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}", chain = 137 }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", chain = 42161 }
fantom = { key = "${ETHERSCAN_API_KEY_FANTOM}", chain = 250 }
metis = { key = "any", chainId = 1088, url = 'https://andromeda-explorer.metis.io/' }
base = { key = "${ETHERSCAN_API_KEY_BASE}", chainId = 8453 }
zkevm = { key = "${ETHERSCAN_API_KEY_ZKEVM}", chainId = 1101 }
gnosis = { key = "${ETHERSCAN_API_KEY_GNOSIS}", chainId = 100 }
bnb = { key = "${ETHERSCAN_API_KEY_BNB}", chainId = 56, url = 'https://api.bscscan.com/api' }
scroll = { key = "${ETHERSCAN_API_KEY_SCROLL}", chainId = 534352 }
zksync = { key = "${ETHERSCAN_API_KEY_ZKSYNC}", chain = 324 }

[fmt]
tab_width = 2
quote_style = 'single'